apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tile-hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tile-hello-world
    spec:
      containers:
      - name: tile-management-console
        image: "registry.ng.bluemix.net/garage_catalog/hello-world:1"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tile-hello-world-service
  labels:
    app: tile-hello-world-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: tile-hello-world-service
  type: LoadBalancer